packages:
  - apps/*
  - packages/*

allowBuilds:
  "@google/genai": false
  "@nestjs/core": true
  esbuild: true
  msgpackr-extract: false
  protobufjs: false
  sharp: true

minimumReleaseAgeExclude:
  - prettier@3.9.5
